api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from api import views
from api.views import ArticlesDetailAPIView, ProfileListAPIView, \
    ProfileDetailAPIView

urlpatterns = [
    path('articles/', views.ArticlesListAPIView.as_view()),
    path('articles/<int:pk>', ArticlesDetailAPIView.as_view()),
    path('profiles/', ProfileListAPIView.as_view()),
    path('profiles/<int:pk>', ProfileDetailAPIView.as_view()),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'


class Articles(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    avatar = models.ImageField(upload_to="images", null=True)

    def __repr__(self):
        return f"{self.title} - {self.content[:100]}"

    def __str__(self):
        return f"{self.title} - {self.content[:100]}"


class Image(models.Model):
    image = models.ImageField(upload_to="images", null=True)
    article = models.ForeignKey("Articles", on_delete=models.CASCADE)

templates/user/activity.html
{% extends 'base.html' %}

{% block content %}


    <div class="container">
        <div class="activity_top">
            <div class="activity_title"><h1>All activity</h1></div>
            <div class="activity_btn"><a href="{% url 'create' %}">
                <button class="btn a">Add activity</button>
            </a></div>
        </div>
        <div class="row">
            <div class="wrap">

                {% for i in activity %}
                    <div class="col-4">
                        <div class="card">
                            <div class="card-body">
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     width="25"
                                     height="25" fill="currentColor"
                                     class="bi bi-bar-chart"
                                     viewBox="0 0 16 16">
                                    <path d="M4 11H2v3h2v-3zm5-4H7v7h2V7zm5-5v12h-2V2h2zm-2-1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1h-2zM6 7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm-5 4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3z"/>
                                </svg>
                                <h3 class="card-text"> {{ i.user }}</h3>
                                <h3 class="card-title"> {{ i.name_activity }}</h3>
                                <p class="card-text"> {{ i.rout_length }}
                                    km</p>
                                <p class="card-text"> {{ i.duration }} min</p>
                                <p class="card-text"> {{ i.calories }} ccal</p>
                                <p class="card-text"> {{ i.date }}</p>
                                <p class="card-text"> {{ i.all_length }}km all
                                    the time</p>
                                <p class="card-text"> {{ i.all_duration }}min
                                    all
                                    the time</p>
                                <br>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>





{% endblock %}

templates/user/create.html
{% extends 'base.html' %}

{% block content %}

    <body>

    <form method="post">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-4">
                <h1>Add activity for {{ user.username }}</h1>

                <label for="user" class="form-label"></label>
                <input name="user" type="text" class="form-control" id="user"
                       placeholder="username" value="{{ user.username }}">

                <label for="weight" class="form-label"></label>
                <input name="weight" type="number" class="form-control"
                       id="weight" placeholder="weight, kg"
                       value="{{ user.weight }}">

                <label for="name_activity" class="form-label"></label>
                <input name="name_activity" type="text" class="form-control"
                       id="name_activity" placeholder="name activity"
                       value="my run">


                <label for="duration" class="form-label"></label>
                <input name="duration" type="number" class="form-control"
                       id="duration" placeholder="duration, min">


                <label for="rout_length" class="form-label"></label>
                <input name="rout_length" type="number" class="form-control"
                       id="rout_length" placeholder="rout length, km">


                <label for="date" class="form-label"></label>
                <input name="date" type="datetime-local" class="form-control"
                       id="date" placeholder="date">

                <button type="submit" class="btn a b">Add</button>
            </div>
        </div>
        </div>
    </form>
    </body>

{% endblock %}

templates/user/delete_profile.html
{% extends 'base.html' %}

{% block content %}

    <body>
    <div class="container">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить
                    пользователя "{{ user.username }}"
                </button>
            </form>
        </div>
    </div>
    </body>

{% endblock %}

templates/user/edit_profile.html
{% extends 'base.html' %}

{% block content %}
    <body>

    <form method="post">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <h1>Форма для редактирования данных
                        пользователя {{ user.username }}</h1>
                </div>

                <div class="row">
                    <div class="col-4">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input name="username" type="text"
                                       class="form-control" id="username"
                                       placeholder="enter username"
                                       value="{{ user.username }}">
                            </div>

                            <div class="mb-3">
                                <label for="country" class="form-label">Country
                                    from</label>
                                <input name="country" type="text"
                                       class="form-control" id="country"
                                       placeholder="Enter country"
                                       value="{{ user.profile.country }}">
                            </div>

                            <div class="mb-3">
                                <label for="weight" class="form-label">My
                                    weight, kg</label>
                                <input name="weight" type="text"
                                       class="form-control" id="weight"
                                       placeholder="weight"
                                       value="{{ user.profile.weight }}">
                            </div>

                            <div class="mb-3">
                                <label for="height" class="form-label">My
                                    height, cm</label>
                                <input name="height" type="text"
                                       class="form-control" id="height"
                                       placeholder="height"
                                       value="{{ user.profile.height }}">
                            </div>

                            <div class="mb-3">
                                <label for="birth_date" class="form-label">birth
                                    date</label>
                                <input name="birth_date" type="date"
                                       class="form-control" id="birth_date"
                                       placeholder="birth_date"
                                       value="{{ user.profile.birth_date }}"
                                       required>
                            </div>

                            <div class="mb-3">
                                <label for="{{ profile.avatar }}"
                                       class="form-label">avatar</label>
                                <input name="avatar" type="file"
                                       class="form-control" id="avatar"
                                       placeholder="avatar">
                            </div>


                            <button type="submit" class="btn btn-primary">
                                Save
                            </button>
                        </form>
                    </div>
                </div>
    </form>
    </body>

{% endblock %}

templates/user/login.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<html>
<head>
    <title>Войти</title>
</head>


<body>

<div class="wrapper">
    <form action="" method="post">
        {% csrf_token %}
        <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
        {{ form.as_p }}

        <button class="btn" type="submit">Enter</button>
    </form>
</div>
</body>

<link rel="stylesheet" href="{% static 'my_login.css' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600;700&display=swap"
      rel="stylesheet">
</html>

templates/user/profile.html
{% extends 'base.html' %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-4 circle">
                {% if user.profile.avatar %}
                    <img src="{{ user.profile.avatar.url }}" class="avatar">
                {% endif %}
                {% for image in profile.image_set.all %}
                    <img src="{{ image.image.url }}" alt="">
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-4">


                <b>{{ user.username }} from {{ user.profile.country }}</b>
                <p>height {{ user.profile.height }} cm</p>
                <p>b-day {{ user.profile.birth_date }}</p>



                <a type="submit" class="btn btn-primary" href="edit/"> Edit
                    user
                    "{{ user.username }}"</a>
                <a type="submit" class="btn btn-danger" href="delete/"> Delete
                    user
                    "{{ user.username }}"</a>

                <h1>Last activity:</h1>

                {% for activity in activity %}
                    <p>{{ activity.rout_length }}km</p>
                    <p>for {{ activity.duration }}min</p>
                    <p>average speed is {{ activity.av_speed }} km/h</p>
                    <br>
                {% endfor %}

            </div>


        </div>

    </div>

{% endblock %}

templates/user/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Регистрация</title>
</head>
<body>
<div class="wrapper register">
    <form action="" method="post" class="form register">
        {% csrf_token %}
        <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
        {{ form.as_p }}
        <button class="btn" href="{% url 'user-register' %}">Create new
            account
        </button>
    </form>
</div>
</body>
<link rel="stylesheet" href="{% static 'my_login.css' %}">
</html>

templates/user/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created. Now you can <a
            href="{% url "login" %}">log in</a>.</p>
{% endblock %}

templates/user/successfully_delete_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<h1>Successfully delete this user</h1>
</body>
</html>